CREATE TABLE DtaUserDetail
(
Id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL
,UserName NVARCHAR(500) NOT NULL
,[Password] VARBINARY(1000) NOT NULL
,FullName NVARCHAR(500)
,Email NVARCHAR(500)
,MobileNumber NVARCHAR(20)
,LoginAttempts INT
,IsActive BIT DEFAULT(1)
,IsDeleted BIT DEFAULT(0)
,CreatedBy VARCHAR(250)
,CreatedDateLocal DATETIME DEFAULT(GETDATE())
,CreatedDateUTC DATETIME DEFAULT(GETUTCDATE())
,UpdatedBy VARCHAR(250)
,UpdatedDateLocal DATETIME
,UpdatedDateUTC DATETIME
)